version: "3.3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /node_modules
      - ./frontend/src:/frontend/src

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8001:8001
    depends_on:
      - database
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./backend:/app

  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_USER: miguel
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: proverb_game
    volumes:
      - /var/lib/mysql

    ports:
      - 3306:3306
